"""Rename logo url

Revision ID: 1f3f9334a5a3
Revises: d0bf20377d60
Create Date: 2024-07-15 17:37:01.096401

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3f9334a5a3'
down_revision: str | None = 'd0bf20377d60'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_url', new_column_name='logo_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_path', new_column_name='logo_url')
    # ### end Alembic commands ###
