"""Add password reset fields

Revision ID: 6dc167e014d2
Revises: 9c0a44739773
Create Date: 2024-07-23 10:22:40.329874

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc167e014d2'
down_revision: str | None = '9c0a44739773'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('active', 'cancelled', 'ended', name='eventstatus'),
               nullable=True)
    op.add_column('users', sa.Column('should_reset_password', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('password_reset_token', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('password_reset_token_expiry', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_reset_token_expiry')
    op.drop_column('users', 'password_reset_token')
    op.drop_column('users', 'should_reset_password')
    op.alter_column('events', 'status',
               existing_type=postgresql.ENUM('active', 'cancelled', 'ended', name='eventstatus'),
               nullable=False)
    # ### end Alembic commands ###
