"""Make logo path required

Revision ID: 9c0a44739773
Revises: 1f3f9334a5a3
Create Date: 2024-07-15 17:44:36.168158

"""
from typing import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0a44739773'
down_revision: str | None = '1f3f9334a5a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_path',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('companies', 'logo_path',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
